export default function getAllStates(t) {
  const stateKeys = [
    "adrar",
    "ainDefla",
    "annaba",
    "batna",
    "bechar",
    "bejaia",
    "biskra",
    "blida",
    "bordjBouArreridj",
    "bouira",
    "boumerdes",
    "chlef",
    "constantine",
    "djelfa",
    "elBayadh",
    "elOued",
    "elTarf",
    "ghardaia",
    "guelma",
    "illizi",
    "jijel",
    "khenchela",
    "laghouat",
    "m'sila",
    "mascara",
    "medea",
    "milal",
    "mostaganem",
    "naama",
    "oran",
    "ouargla",
    "oumElBouaghi",
    "relizane",
    "saida",
    "sidiBelAbbes",
    "skikda",
    "soukAhras",
    "tamanrasset",
    "tebessa",
    "tiaret",
    "tindouf",
    "tipaza",
    "tissemsilt",
    "tiziOuzou",
    "tlemcen",
  ];
  const stateList = stateKeys.map((stateKey) => {
    return { name: t(`states:${stateKey}`) };
  });
  return stateList;
}
